# **PYTHON FUNDAMENTALS PRACTICE QUESTIONS FOR DATASCIENCE**

### **LIST PRACTICE QUESTIONS**

In [255]:
from numpy.ma.core import left_shift

# Print alternate elements.
nums = [10, 20, 30, 40, 50]
print(nums[::2])
# reverse using slicing
print(nums[::-1])
#Change first element to 100.
nums[0]=100
nums[1]=200
print(nums)
#Update multiple elements using slicing.
nums[0:2]=[10, 20]
print(nums)

[10, 30, 50]
[50, 40, 30, 20, 10]
[100, 200, 30, 40, 50]
[10, 20, 30, 40, 50]

In [256]:
# Add 60 to the end of the list using append().
nums.append(60)
# Add [70, 80,20,20] to the list using extend().
nums.extend([70,80,20,20,20])
# Insert 25 at index 1.
nums.insert(1,25)
print(nums)

[10, 25, 20, 30, 40, 50, 60, 70, 80, 20, 20, 20]

In [257]:
# Remove 30 using remove().
nums.remove(30)
# Remove last element using pop().
nums.pop(-1)
# Remove element at index 2.
del nums[2]
# Clear the entire list using clear().
nums.clear()

In [258]:
nums = [50,10,40,20,30]
#Sort list in ascending order.
nums.sort()
print(nums)
#Sort list in descending order.
nums.sort(reverse=True)
print(nums)
#Use sorted() instead of sort().
new_list = sorted(nums)
new_list_rev = sorted(nums, reverse=True)
print("sorted list using sorted():",new_list)
print("reverse sorted list using sorted():",new_list_rev)
#Check difference between sort() and sorted().
print("""
         1) sorted() works on all data types while sort() only works on list.
         2) sorted() does not change original list while sort() changes original list.
         3) sort() gives none(can not use in print) as output while sorted() gives sorted list.
         """)

[10, 20, 30, 40, 50]
[50, 40, 30, 20, 10]
sorted list using sorted(): [10, 20, 30, 40, 50]
reverse sorted list using sorted(): [50, 40, 30, 20, 10]

         1) sorted() works on all data types while sort() only works on list.
         2) sorted() does not change original list while sort() changes original list.
         3) sort() gives none(can not use in print) as output while sorted() gives sorted list.

In [259]:
fruits = ["banana","apple","mango"]
n=[10,20,10,30]
#Find index of "apple"
print(fruits.index("apple"))
print(n.index(10))
print(fruits.count("banana"))
print(n.count(10))

1
0
1
2

In [260]:
# a copy using copy().
a=[1,2,3,4,5,6]
d=[2,3,4,5,6,7]
e=[]
b= a.copy()
print("a:",a)
print("b:",b)
# Create copy using slicing.
c=a[:]
print("c:",c)
# Check difference between:a = b and a = b.copy()
a.append(7)
print(f"a after append: {a}")
b.extend([8,9])
print(f"b after extend: {b}")
e=d
print("d:",d)
print("e:",e)
d.remove(7)
e.remove(6)
print("d after remove 7:",d)
print("e after remove 6:",e)

a: [1, 2, 3, 4, 5, 6]
b: [1, 2, 3, 4, 5, 6]
c: [1, 2, 3, 4, 5, 6]
a after append: [1, 2, 3, 4, 5, 6, 7]
b after extend: [1, 2, 3, 4, 5, 6, 8, 9]
d: [2, 3, 4, 5, 6, 7]
e: [2, 3, 4, 5, 6, 7]
d after remove 7: [2, 3, 4, 5]
e after remove 6: [2, 3, 4, 5]

### **DICTIONARY PRACTICE QUESTIONS**

In [261]:
student = {
    "name": "Satwik",
    "age": 19,
    "course": "CSE"
}
# Access "name" using key.
print(student["name"])
# Access "age" using get().
print(student.get("age","not found"))
# Add key "city" with value "Bangalore".
student["city"]="Bangalore"
# Update age to 20.
student["age"]=21
# Add multiple keys using update().
student.update({"Department":"B.TECH","course":"CSE DS"})
print(student)

Satwik
19
{'name': 'Satwik', 'age': 21, 'course': 'CSE DS', 'city': 'Bangalore', 'Department': 'B.TECH'}

In [262]:
# Print all keys.
print(student.keys())
# Print all values.
print(student.values())
# Print all key-value pairs using items().
print(student.items())

dict_keys(['name', 'age', 'course', 'city', 'Department'])
dict_values(['Satwik', 21, 'CSE DS', 'Bangalore', 'B.TECH'])
dict_items([('name', 'Satwik'), ('age', 21), ('course', 'CSE DS'), ('city', 'Bangalore'), ('Department', 'B.TECH')])

In [113]:
#Create dictionary copy using copy().
student2=student.copy()
print(student2)
#Check if "name" key exists.
print("name" in student)
#Find length using len().
len(student)

{'name': 'Satwik', 'age': 21, 'course': 'CSE DS', 'city': 'Bangalore', 'Department': 'B.TECH'}
True

5

In [263]:
# Remove "age" using pop().
student.pop("age")
print(student)
# Remove last inserted item using popitem().
student.popitem()
print(student)
# Delete key "course" using del.
del student["course"]
print(student)
# Clear entire dictionary.
student.clear()

{'name': 'Satwik', 'course': 'CSE DS', 'city': 'Bangalore', 'Department': 'B.TECH'}
{'name': 'Satwik', 'course': 'CSE DS', 'city': 'Bangalore'}
{'name': 'Satwik', 'city': 'Bangalore'}

In [264]:
# Merge two dictionaries manually using loops.
d1 = {"A":90,"B":80,"C":90,"D":80}
d2 = {"e":90,"f":80,"g":90,"h":90}
d3 = d1|d2
print(d3)

{'A': 90, 'B': 80, 'C': 90, 'D': 80, 'e': 90, 'f': 80, 'g': 90, 'h': 90}

###  **LOOPS PRACTICE QUESTIONS**

In [266]:
# use loops to find length of list
l_length=0
l=[1,2,3,4,5,6,7,8,9,10]
for i in l:
    l_count=l_length+1
print(l_length)

0

In [267]:
# use loops to find maximum element of list
max_ele=0
for i in l:
    if i > max_ele:
        max_ele=i
    else:
        continue
print(max_ele)

10

In [268]:
# use loops to find sum of all elements of list
sum_l=0
for i in l:
    sum_l=sum+i
print(sum_l)

350

In [269]:
# use loops to find even or odd elements of list
even =0
odd =0
for i in l:
    if i%2== 0:
        even +=1
    else:
        odd +=1
print("even =",even)
print("odd =",odd)

even = 5
odd = 5

In [273]:
for i in range(1,101):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [272]:
# Print multiplication table of a given number.
n = int(input("Enter a number: "))
for i in range(1,11):
    print(f"{n}x{i} = {n*i}")

5x1 = 5
5x2 = 10
5x3 = 15
5x4 = 20
5x5 = 25
5x6 = 30
5x7 = 35
5x8 = 40
5x9 = 45
5x10 = 50

In [275]:
# Find sum of digits.
num = 123
sum = 0
for i in str(num):
    sum += int(i)
print(sum)

6

In [270]:
# Count digits in a number.
num = "123"
count=0
for i in num:
    count += 1
print(count)

3

### **MIXED PRACTICE QUESTION**

In [235]:
# reverse list by using loop
list1=[1,2,3,4,5,6,7,8,9,10]
rev=[]
for j in list1:
        j = -j
        rev.append(list1[j])
print(rev)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [ ]:
#Remove duplicate values from a list.
l1=[3,5,6,5,6,3,3,6,6,6,3,1]
unique=set(l1)
unique_list = []
for i in unique:
    unique_list.append(i)
print(unique_list)

In [236]:
# Count how many times each number appears in a list.
l1=[3,5,6,5,6,3,3,6,6,6,3,1]
count={}
for i in l1:
    count[i]=count.get(i,0)+1
print(count)

{1: 1, 4: 1, 5: 1, 6: 2, 36: 1}

In [237]:
#Separate Positive and Negative of a list and create two list: Positive numbers and Negative numbers
mixed_list=[1,35,5,35,35,-3,-7,-34,-6]
positive_list=[]
negative_list=[]
for i in mixed_list:
    if i>0:
        positive_list.append(i)
    elif i<0:
        negative_list.append(i)
positive_list.sort()
negative_list.sort()
print(positive_list)
print(negative_list)

[1, 5, 35, 35, 35]
[-34, -7, -6, -3]

In [178]:
# Reverse a number.
num= 123
reversed_num = []
num_reversed = ''
for i in str(num):
    reversed_num.append(i)
    reversed_num.reverse()
for i in reversed_num:
    num_reversed = num_reversed + str(i)
print(int(num_reversed))

312

In [274]:
# Find common elements between two lists.
l1=[1,4,5,6,36,6]
l2 =[1,35,564,4,6,7]
common=[]
for i in l1:
    for j in l2:
        if i==j:
            if i not in common:
               common.append(i)
print(common)

[1, 4, 6]

In [284]:
# Find missing number from:
incomplete = [1,2,3,5]
for i in range(1,len(incomplete)+1):
    if i==incomplete[i-1]:
        continue
    else:
        incomplete.append(i)
print(incomplete)

[1, 2, 3, 5, 4]

In [239]:
# Create a dictionary of student marks and print all students scoring above 85.
marks = {"A":90,"B":80,"C":90,"D":80}
for key,value in marks.items():
    if value > 85:
        print(key,":",value)

A : 90
C : 90

In [240]:
# fing total bill
cart = {
    "apple":50,
    "banana":20,
    "milk":40
}
total_bill =0
for key,value in cart.items():
    total_bill += value
print(total_bill)

110

In [241]:
# Count frequency of characters in a string.
word = "banana"
count = {}
for letter in word:
    count[letter]=count.get(letter,0)+1
print(count)

{'b': 1, 'a': 3, 'n': 2}

In [276]:
# calculate attendance of students
student_attendance = ["A","B","A","C","B","A"]
student_attendance_2={}
for i in student_attendance:
    student_attendance_2[i] = student_attendance_2.get(i,0)+1
print(student_attendance_2)

{'A': 3, 'B': 2, 'C': 1}

In [ ]:
# Rotate list left and right by one position
original = [1,2,3,4,5,6,7,8,9,10]
left_shift=[]

for i in original:
    if i == 1:
       left_shift.append(original[-1])
    if i > 0 and i < len(original):
           left_shift.append(i)
print(f"left_shift={left_shift}")


right_shift=[]
for i in original:
    if i == 1:
        temp=original[0]
        continue
    right_shift.append(i)
    if i ==10:
        right_shift.append(temp)
print(f"right_shift={right_shift}")

left_shift=[10, 1, 2, 3, 4, 5, 6, 7, 8, 9]
right_shift=[2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [242]:
# Swap keys and values.
dict1={'b': 1, 'a': 3, 'n': 2}
swapped = {}
for key in dict1:
    value = dict1[key]
    swapped[value] = key
print(swapped)

{1: 'b', 3: 'a', 2: 'n'}

In [243]:
student = {
    "A": 90,
    "B": 90,
    "C": 80
}
swapped = {}

for key in student:
    value = student[key]

    if value not in swapped:
        swapped[value] = []

    swapped[value].append(key)

print(swapped)

{90: ['A', 'B'], 80: ['C']}

In [244]:
# Find the sum of all values in a dictionary.
marks = {"A":90,"B":80,"C":90,"D":80}
sum=0
for key,value in marks.items():
    sum+=value
print(sum)

340

In [245]:
#Check if a given key exists in dictionary without using in
fruits = {'apple':2, 'banana':1}
key_check = input("Enter a key: ")
found = False
for key in fruits:
    if key == key_check:
        found = True
        break
print(found)

True

In [246]:
# Count total keys in a dictionary without using len().
marks = {"A":90,"B":80,"C":90,"D":80}
keys=0
for key in marks:
    keys += 1
print(keys)

4

In [247]:
# Find the student with highest marks.
marks = {"A":90,"B":80,"C":90,"D":80}
max_marks=0
for key,value in marks.items():
    if value > max_marks:
        max_marks=value
print(max_marks)

90

In [289]:
# Increase salary by 10%.
salary = { "A":1000, "B":2000 }
for key,value in salary.items():
    salary[key] = value + (value * 0.1)
print(salary)

{'A': 1100.0, 'B': 2200.0}

In [290]:
# Count vowels in a string.
string = "afjfdfornvrieu"
vowel = ['a', 'e', 'i', 'o', 'u']
count={}
for i in string:
    if i in vowel:
       count[i]=count.get(i,0)+1
print(count)

{'a': 1, 'o': 1, 'i': 1, 'e': 1, 'u': 1}

### **IMPORTANT PATTERN QUESTIONS**

In [182]:
# Check if a number is palindrome.
num = 121
reversed_num=''
for i in str(num):
    reversed_num += str(i)
if int(reversed_num) == num:
    print("Palindrome")
else:
    print("Not Palindrome")

Palindrome

In [196]:
# Find factorial of a number using loop.
n = int(input("Enter a number: "))
factorial = 1
for i in range(n,1,-1):
    if n == 1 or n == 0:
        break
    else:
         factorial = factorial * i
print(f"factorial of {n} is {factorial}")

factorial of 5 is 120

In [366]:
# Fibonacci series
n = int(input("Enter a number: "))
a,b=0,1
fibonacci=[]
for i in range(1,n+1):
    fibonacci.append(a)
    a,b=b,a+b
print(f"fibonacci = {fibonacci}")

 fibonacci = [0, 1, 1, 2, 3]

In [168]:
#Check whether a number is prime.
n = int(input("Enter a number: "))
if n <= 1:
    print("Not Prime or Composite")
for i in range(2,int(n**0.5) + 1):
    if n % i == 0:
        print("Not Prime")
        break
    else:
        print("Prime")

Prime

In [197]:
# Check if a number is an Armstrong number.
num=1634
length = len(str(num))
sum = 0
for i in str(num):
    sum += int(i)**length
if int(sum) == num:
    print("Armstrong")
else:
    print("Not Armstrong")

Armstrong

In [212]:
# Nested Loop Pattern:
n = int(input("Enter a number: "))
for i in range(1, n + 1):
    print(i * "*")

*
**
***
****
*****

In [225]:
n = int(input("Enter a number: "))
for i in range(n, 0,-1):
    print(i * "*")

*****
****
***
**
*

In [220]:
n = int(input("Enter a number: "))
for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j,end = "")
    print()

1
12
123
1234
12345

### **INVENTORY MANAGEMENT MINI PROJECT**

In [ ]:
#Inventory management
inventory = {"apple": 5, "banana": 2}
while True:
    print("""
PRESS
1. Show inventory stock
2. Search stock
3. Add new stock
4. Remove stock
5. Update value of stock)
6. Exit
    """)

    option = input("Enter an option: ")

    if option == "1":
        print(inventory)

    elif option == "2":
        search = input("Enter stock name: ").lower()
        if search in inventory:
            print(f"{search}: {inventory[search]}")
        else:
            print("Stock not found")

    elif option == "3":
        key = input("Enter stock name: ").lower()
        value = int(input("Enter stock quantity: "))
        if key not in inventory:
            inventory[key] = value
        else:
            inventory[key] += value
        print("Stock added successfully")

    elif option == "4":
        delete_option = input("Fully remove or selective items (F/S): ").lower()
        if delete_option == "s":
            delete_key = input("Enter stock name: ").lower()
            if delete_key in inventory:
                delete_value = int(input("Enter quantity to remove: "))
                del inventory[delete_key]
                print("Stock updated")
            else:
                print("Stock not found")
        elif delete_option == "f":
            inventory.clear()
            print("Inventory cleared")
        else:
            print("Invalid choice")

    elif option == "5":
        update_key = input("Enter stock name: ").lower()
        if update_key in inventory:
            update_value = int(input("Enter new quantity: "))
            inventory[update_key] = update_value
            print("Inventory updated")
        else:
            print("Stock not found")

    elif option == "6":
        print("Exiting program...")
        break

    else:
        print("Invalid option")

### **PANDAS PRACTICE QUESTIONS**

In [1]:
Brics = { "country":["Brazil", "Russia", "India", "China", "South Africa"],
         "capital":["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
         "area":[8.516, 17.10, 3.286, 9.597, 1.221],
         "population":[200.4, 143.5, 1252, 1357, 52.98] }
import pandas as pd
# import pandas and covert dictionary to pandas
brics_df = pd.DataFrame(Brics)
brics_df

        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [3]:
# give custom index to dataframe
brics_df.index = ["BR","RU","IND","CH","SA"]
brics_df

          country    capital    area  population
BR         Brazil   Brasilia   8.516      200.40
RU         Russia     Moscow  17.100      143.50
IND         India  New Delhi   3.286     1252.00
CH          China    Beijing   9.597     1357.00
SA   South Africa   Pretoria   1.221       52.98

In [4]:
# importing csv to dataframe
brics_df = pd.read_csv("D:/PROGRAMS/PYTHON PROJECTS/PythonProject/countries.csv")
brics_df

  country_code       country    capital    area  population
0           BR        Brazil   Brasilia   8.516      200.40
1           RU        Russia     Moscow  17.100      143.50
2           IN         India  New Delhi   3.286     1252.00
3           CH         China    Beijing   9.597     1357.00
4           SA  South Africa   Pretoria   1.221       52.98

In [43]:
# removing index column
brics_df = pd.read_csv("D:/PROGRAMS/PYTHON PROJECTS/PythonProject/countries.csv",index_col=0)
brics_df

                   country    capital    area  population
country_code
BR                  Brazil   Brasilia   8.516      200.40
RU                  Russia     Moscow  17.100      143.50
IN                   India  New Delhi   3.286     1252.00
CH                   China    Beijing   9.597     1357.00
SA            South Africa   Pretoria   1.221       52.98

In [44]:
# column access
# as series
print(brics_df["country"])
print(f"data type of brics_df = {type(brics_df)}")
print(f"data type of country column = {type(brics_df["country"])}")

# as dataframe
print(brics_df[["country"]])
print(f"data type of country column = {type(brics_df[["country"]])}")

#multiple column access
brics_df[["country", "capital"]]

country_code
BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: str
data type of brics_df = <class 'pandas.DataFrame'>
data type of country column = <class 'pandas.Series'>
                   country
country_code
BR                  Brazil
RU                  Russia
IN                   India
CH                   China
SA            South Africa
data type of country column = <class 'pandas.DataFrame'>

                   country    capital
country_code
BR                  Brazil   Brasilia
RU                  Russia     Moscow
IN                   India  New Delhi
CH                   China    Beijing
SA            South Africa   Pretoria

In [45]:
# row access
brics_df[1:4]

             country    capital    area  population
country_code
RU            Russia     Moscow  17.100       143.5
IN             India  New Delhi   3.286      1252.0
CH             China    Beijing   9.597      1357.0

In [51]:
# loc

print(brics_df.loc["RU"]) # as series
print("")
print(brics_df.loc[["IN"]]) # as dataframe
print("")
print(brics_df.loc[["RU", "IN" ]])  # multiple rows
print("")
print(brics_df.loc[["RU", "IN" ],["country","capital"]]) # multiple rows and columns
print("")
brics_df.loc[:,["country","capital"]] # all rows with column of country and capital

country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object

             country    capital   area  population
country_code
IN             India  New Delhi  3.286      1252.0

             country    capital    area  population
country_code
RU            Russia     Moscow  17.100       143.5
IN             India  New Delhi   3.286      1252.0

             country    capital
country_code
RU            Russia     Moscow
IN             India  New Delhi

                   country    capital
country_code
BR                  Brazil   Brasilia
RU                  Russia     Moscow
IN                   India  New Delhi
CH                   China    Beijing
SA            South Africa   Pretoria

In [13]:
brics_df.iloc[1]

country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object

In [14]:
brics_df.iloc[[1,2,3]]

             country    capital    area  population
country_code
RU            Russia     Moscow  17.100       143.5
IN             India  New Delhi   3.286      1252.0
CH             China    Beijing   9.597      1357.0

In [16]:
brics_df.iloc[[1,2,3],[0,1]]

             country    capital
country_code
RU            Russia     Moscow
IN             India  New Delhi
CH             China    Beijing

In [17]:
brics_df.iloc[:,[0,1]]

                   country    capital
country_code
BR                  Brazil   Brasilia
RU                  Russia     Moscow
IN                   India  New Delhi
CH                   China    Beijing
SA            South Africa   Pretoria

In [20]:
brics_df.head()
brics_df.tail()

                   country    capital    area  population
country_code
BR                  Brazil   Brasilia   8.516      200.40
RU                  Russia     Moscow  17.100      143.50
IN                   India  New Delhi   3.286     1252.00
CH                   China    Beijing   9.597     1357.00
SA            South Africa   Pretoria   1.221       52.98

In [23]:
brics_df.shape

(5, 4)

In [82]:
brics_df.dtypes

country           str
capital           str
area          float64
population    float64
dtype: object

In [24]:
brics_df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, BR to SA
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     5 non-null      str
 1   capital     5 non-null      str
 2   area        5 non-null      float64
 3   population  5 non-null      float64
dtypes: float64(2), str(2)
memory usage: 372.0+ bytes

In [25]:
brics_df.describe()

            area   population
count   5.000000     5.000000
mean    7.944000   601.176000
std     6.200557   645.261454
min     1.221000    52.980000
25%     3.286000   143.500000
50%     8.516000   200.400000
75%     9.597000  1252.000000
max    17.100000  1357.000000

In [26]:
brics_df.columns

Index(['country', 'capital', 'area', 'population'], dtype='str')

In [27]:
brics_df.index

Index(['BR', 'RU', 'IN', 'CH', 'SA'], dtype='str', name='country_code')

In [29]:
brics_df.sort_values("area")

                   country    capital    area  population
country_code
SA            South Africa   Pretoria   1.221       52.98
IN                   India  New Delhi   3.286     1252.00
BR                  Brazil   Brasilia   8.516      200.40
CH                   China    Beijing   9.597     1357.00
RU                  Russia     Moscow  17.100      143.50

In [31]:
brics_df.sort_values("population", ascending=False)

                   country    capital    area  population
country_code
CH                   China    Beijing   9.597     1357.00
IN                   India  New Delhi   3.286     1252.00
BR                  Brazil   Brasilia   8.516      200.40
RU                  Russia     Moscow  17.100      143.50
SA            South Africa   Pretoria   1.221       52.98

In [30]:
brics_df.sort_values(["population","area"],ascending=[True,False])

                   country    capital    area  population
country_code
SA            South Africa   Pretoria   1.221       52.98
RU                  Russia     Moscow  17.100      143.50
BR                  Brazil   Brasilia   8.516      200.40
IN                   India  New Delhi   3.286     1252.00
CH                   China    Beijing   9.597     1357.00

In [32]:
brics_df[brics_df["population"]>1000]

             country    capital   area  population
country_code
IN             India  New Delhi  3.286      1252.0
CH             China    Beijing  9.597      1357.0

In [33]:
brics_df[brics_df["country"]=="India"]

             country    capital   area  population
country_code
IN             India  New Delhi  3.286      1252.0

In [56]:
brics_df[(brics_df["area"]>8) & (brics_df["population"]>600)]

             country  capital   area  population
country_code
CH             China  Beijing  9.597      1357.0

In [53]:
brics_df[brics_df["country"].isin(["India","China"])]

             country    capital   area  population
country_code
IN             India  New Delhi  3.286      1252.0
CH             China    Beijing  9.597      1357.0

In [73]:
# Summarizing numerical data: .sum(), .min(), .max(), .mean(), .mode(), .median(), .var(), .std(), .quartile()
print(brics_df["area"].mean())

# aggregate() method:
def pct30(column):
    return column.quantile(0.3)
def pct75(column):
    return column.quantile(0.75)
# brics_df[["area","population"]].aggregate(pct30)
# brics_df["area"].aggregate(pct30)
# brics_df["population"].aggregate(pct30,pct75)
brics_df[["area","population"]].aggregate([pct75,pct30])

# cumulative statistics
brics_df["area"].cumprod()
brics_df["population"].cummin()
brics_df["population"].cummax()
brics_df["population"].cumsum()

7.944

        area  population
pct75  9.597     1252.00
pct30  4.332      154.88

In [79]:
brics_df["country"].value_counts()
brics_df["country"].value_counts(sort=True)

country
Brazil          1
Russia          1
India           1
China           1
South Africa    1
Name: count, dtype: int64

In [89]:
brics_df["Area_Mean"]=brics_df["area"].mean()
brics_df["Population_Mean"]=brics_df["population"].mean()
brics_df

,country,capital,area,population,HI,Area_Mean,Population_Mean
country_code,,,,,,,
BR,Brazil,Brasilia,8.516,200.40,hello,7.944,601.176
RU,Russia,Moscow,17.100,143.50,hello,7.944,601.176
IN,India,New Delhi,3.286,1252.00,hello,7.944,601.176
CH,China,Beijing,9.597,1357.00,hello,7.944,601.176
SA,South Africa,Pretoria,1.221,52.98,hello,7.944,601.176

In [100]:
brics_df.drop("HI",axis=1)

,country,capital,area,population,Area_Mean,Population_Mean
country_code,,,,,,
BR,Brazil,Brasilia,8.516,200.40,7.944,601.176
RU,Russia,Moscow,17.100,143.50,7.944,601.176
IN,India,New Delhi,3.286,1252.00,7.944,601.176
CH,China,Beijing,9.597,1357.00,7.944,601.176
SA,South Africa,Pretoria,1.221,52.98,7.944,601.176

In [102]:
brics_df.rename(columns={"Area_Mean":"A_mean"})

,country,capital,area,population,Area_Mean,Population_Mean
country_code,,,,,,
BR,Brazil,Brasilia,8.516,200.40,7.944,601.176
RU,Russia,Moscow,17.100,143.50,7.944,601.176
IN,India,New Delhi,3.286,1252.00,7.944,601.176
CH,China,Beijing,9.597,1357.00,7.944,601.176
SA,South Africa,Pretoria,1.221,52.98,7.944,601.176

In [117]:
brics_df.isna()

,country,capital,area,population,HI,Area_Mean,Population_Mean
country_code,,,,,,,
BR,False,False,False,False,False,False,False
RU,False,False,False,False,False,False,False
IN,False,False,False,False,False,False,False
CH,False,False,False,False,False,False,False
SA,False,False,False,False,False,False,False

In [118]:
brics_df.isna().any()

country            False
capital            False
area               False
population         False
HI                 False
Area_Mean          False
Population_Mean    False
dtype: bool