# **PYTHON FOUNDATIONS PRACTICE SET - 2**

### **NUMPY**

In [2]:
import numpy as np

In [12]:
# create 1D,2D,3D array
arr = np.array([1,2,3,4,5,6,7])
print(f"1D array: {arr}")
arr2 = np.array([[1,2],[3,4]])
print(f"2D array:\n {arr2}")
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f"3D array:\n {arr3}")
arr4 = np.array([1,2,3,4,5],dtype="float")
print(f"data type converted to float: {arr4}")

1D array: [1 2 3 4 5 6 7]
2D array:
 [[1 2]
 [3 4]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
data type converted to float: [1. 2. 3. 4. 5.]

In [29]:
# array properties:
#shape
print(f"Shape of arr3: {arr3.shape}")
#size
print(f"Size of arr3: {arr3.size}")
#dtype
print(f"Data Type of elements: {arr3.dtype}")
#ndim
print(f"Dimensions of arr3: {arr3.ndim}")
print(arr3.itemsize)
print(len(arr3))

Shape of arr3: (2, 2, 2)
Size of arr3: 8
Data Type of elements: int64
Dimensions of arr3: 3
8
2

In [73]:
# Accessing elements:
# First element of arr
print(f"First element: {arr[0]}")
# Last element of arr
print(f"Last element: {arr[-1]}")
# Middle element of arr
print(f"Middle element: {arr[len(arr)//2]}")
# Reverse order of arr
print(f"Reverse: {arr[::-1]}")
# Skip 2 steps of arr
print(f"Skip two steps: {arr[::2]}")
# 2d array
print(f" 2D array: \n{arr2[:]}")
# first column of 2D
print(f"1st column of arr2: {arr2[:,0]}")
# second row of arr2
print(f"2nd row of arr2: {arr2[1,:]}")

First element: 1
Last element: 7
Middle element: 4
Reverse: [7 6 5 4 3 2 1]
Skip two steps: [1 3 5 7]
 2D array:
[[1 2]
 [3 4]]
1st column of arr2: [1 3]
2nd row of arr2: [3 4]

In [26]:
#Special arrays
# zero matrix
np.zeros((3,3), dtype="int")
# ones matrix
np.ones((3,3), dtype="int")
# identity matrix
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [30]:
# Create an array from 1 to 20 with step size 2.
np.arange(1,21,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
# create a array with evenly spaced distance of 5 elements from 1 to 10
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
# Reshaping
a = np.array([1,2,3,4,5,6])
# Reshape 1d to 2d with 2 rows and 3 columns
print(f"1D to 2D: \n{a.reshape(2,3)}")
# Flatten it back to 1D
print(f"Flatten to 1D: {a.flatten()}")
# Split a into 3 parts
print(f"Split into 3 parts: {np.split(a,3)}")

print("""
Use ravel() when:
    - you need 1D quickly
    - memory efficiency matters

Use flatten() when:
    - you want independent copy
    - Quick memory trick:

ravel = road (same path)
flatten = photocopy
""")

1D to 2D:
[[1 2 3]
 [4 5 6]]
Flatten to 1D: [1 2 3 4 5 6]
Split into 3 parts: [array([1, 2]), array([3, 4]), array([5, 6])]

Use ravel() when:
    - you need 1D quickly
    - memory efficiency matters

Use flatten() when:
    - you want independent copy
    - Quick memory trick:

ravel = road (same path)
flatten = photocopy

In [35]:
# mathematical operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])
print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")
print(f"a / b = {a / b}")
print(f"square root of [1,2,3,4,5] = {np.sqrt(a)}")
print(f"power of 2 on [1,2,3,4,5] = {np.power(b, 2)}")
# scalar operations also known as broadcasting
print(f"a + 10 = {a + 10}")
print(f"a - 10 = {a - 10}")
print(f"a * 10 = {a * 10}")
print(f"a / 10 = {a / 10}")

a + b = [ 2  4  6  8 10]
a - b = [0 0 0 0 0]
a * b = [ 1  4  9 16 25]
a / b = [1. 1. 1. 1. 1.]
square root of [1,2,3,4,5] = [1.         1.41421356 1.73205081 2.         2.23606798]
power of 2 on [1,2,3,4,5] = [ 1  4  9 16 25]
a + 10 = [11 12 13 14 15]
a - 10 = [-9 -8 -7 -6 -5]
a * 10 = [10 20 30 40 50]
a / 10 = [0.1 0.2 0.3 0.4 0.5]

In [88]:
# Find largest and smallest number also Mean, Median, Sum, standard deviation, variance using NumPy functions
arr = np.array([10, 20, 30, 40, 50,50])
print(f"max number = {np.max(arr)}")
print(f"min number = {np.min(arr)}")
print(f"mean number = {np.mean(arr)}")
print(f"median number = {np.median(arr)}")
print(f"sum number = {np.sum(arr)}")
print(f"final product = {np.prod(arr)}")
print(f"standard deviation = {np.std(arr)}")
print(f"variance = {np.var(arr)}")
print(f"cumsum = {np.cumsum(arr)}")
print(f"cumprod = {np.cumprod(arr)}")
print(f"quantile (.25,.5,.75) = {np.quantile(arr,[.25,.5,.75])}")
print(f"percentile (25%,50%,75%) = {np.percentile(arr,[25,50,75])}")

max number = 50
min number = 10
mean number = 33.333333333333336
median number = 35.0
sum number = 200
final product = 600000000
standard deviation = 14.9071198499986
variance = 222.22222222222226
cumsum = [ 10  30  60 100 150 200]
cumprod = [       10       200      6000    240000  12000000 600000000]
quantile (.25,.5,.75) = [22.5 35.  47.5]
percentile (25%,50%,75%) = [22.5 35.  47.5]

In [54]:
# axis operation
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

print(f"Sum along y axis: {np.sum(a, axis=0)}")
print(f"min along y axis: {np.min(a, axis=0)}")
print(f"max along y axis: {np.max(a, axis=0)}")
print(f"max along y axis: {np.mean(a, axis=0)}")

print(f"sum along x axis: {np.sum(a, axis=1)}")
print(f"min along x axis: {np.min(a, axis=1)}")
print(f"max along x axis: {np.max(a, axis=1)}")
print(f"max along x axis: {np.mean(a, axis=1)}")

Sum along y axis: [ 7  9 11 13 15]
min along y axis: [1 2 3 4 5]
max along y axis: [ 6  7  8  9 10]
max along y axis: [3.5 4.5 5.5 6.5 7.5]
sum along x axis: [15 40]
min along x axis: [1 6]
max along x axis: [ 5 10]
max along x axis: [3. 8.]

In [74]:
# Boolean Filtering
a = np.array([12, -5, 8, 21, 30, 45, 3, 50, 60, -2, 17])

print(F'a: {a}')
print(f'elements greater then 10: {a[a > 10]}')
print(f"Even: {a[a % 2 == 0]}")
a[a < 0]=0
print(f"after converting: {a}")
print(f"elements greater than 20 and less than 50: {a[ ( a > 20 ) & (a < 50)]}")
a = a[a>0]
print(f"after removing zeros: {a}")

a: [12 -5  8 21 30 45  3 50 60 -2 17]
elements greater then 10: [12 21 30 45 50 60 17]
Even: [12  8 30 50 60 -2]
after converting: [12  0  8 21 30 45  3 50 60  0 17]
elements greater than 20 and less than 50: [21 30 45]
after removing zeros: [12  8 21 30 45  3 50 60 17]

In [94]:
# Stacking arrays
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,2,3,4,5,6,7,8,9])
print(f"Vertical Stack: \n{np.vstack((a,b),dtype=int)}")
print(f"Horizontal stack: \n{np.hstack((a,b),dtype=int)}")

Vertical Stack:
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
Horizontal stack:
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]

In [84]:
matrix1 = np.array([[1, 2],
                    [3, 4]])
matrix2 = np.array([[5, 6],
                    [7, 8]])

# Add two matrices.
print(f" matrix1 + matrix2 = \n {matrix1 + matrix2}")
# Sub two matrices.
print(f" matrix1 - matrix2 = \n {matrix1 - matrix2}")
# Multiply two matrices.
print(f" matrix1 * matrix2 = \n {matrix1 * matrix2}")
# Divide two matrices.
print(f" matrix1 / matrix2 = \n {matrix1 / matrix2}")
# matrix multiplication
print(f" matrix1 x matrix2 = \n {np.matmul(matrix1, matrix2)}")
# Dot product
print(f"dot product = \n {np.dot(matrix1, matrix2)}")
# Transpose
print(f" transpose = \n {np.transpose(matrix1)}")
# determinant
print(f"determinant = {np.linalg.det(matrix1)}")
# inverse
print(f"inverse = \n {np.linalg.inv(matrix1)}")
# eigen values
print(f"eigen values = \n {np.linalg.eig(matrix1)}")
# trace
print(f" sum of all diagonal elements(trace)= {np.trace(matrix1)}")
#diagonal elements
print(f'diagonal elements = {np.diag(matrix1)}')

 matrix1 + matrix2 =
 [[ 6  8]
 [10 12]]
 matrix1 - matrix2 =
 [[-4 -4]
 [-4 -4]]
 matrix1 * matrix2 =
 [[ 5 12]
 [21 32]]
 matrix1 / matrix2 =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
 matrix1 x matrix2 =
 [[19 22]
 [43 50]]
dot product =
 [[19 22]
 [43 50]]
 transpose =
 [[1 3]
 [2 4]]
determinant = -2.0000000000000004
inverse =
 [[-2.   1. ]
 [ 1.5 -0.5]]
eigen values =
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
 sum of all diagonal elements = 5
diagonal elements = [1 4]

In [96]:
# NumPy using the random module.

# 1.generate random integers by using np.random.randint(start, end, size)
arr = np.random.randint(1, 101, 5)
print(f"array with 5 random integers from 1 to 100: {arr}")

# 2.generate matrix
mat = np.random.randint(1, 11, (3, 3))
print(f"3x3 matrix with random integers from 1 to 10: \n {mat}")

# 3.Generate Random Float Values by np.random.rand(size) by default Range is between 0 and 1
arr = np.random.rand(3, 3)
print(f"3x3 matrix with random floating: \n{arr}")

# 4.Random Floats in Custom Range by using np.random.uniform(start,stop,size)
arr = np.random.uniform(10, 20, (3, 3))
print(f"3x3 matrix with random floating from 10-20: \n{arr}")

print("""
- seed() is used to make random numbers repeatable.
- np.random.seed(number) --> can be any number
- Same seed → same random numbers
  Different seed → different numbers
""")

array with 5 random integers from 1 to 100: [18 30 89 68 12]
3x3 matrix with random integers from 1 to 10:
 [[ 6  5  5]
 [ 9  3  2]
 [10  9  3]]
3x3 matrix with random floating:
[[0.59567984 0.5731539  0.622582  ]
 [0.42377308 0.28005425 0.95869448]
 [0.75519617 0.04716139 0.6850509 ]]
3x3 matrix with random floating from 10-20:
[[15.91791985 19.5662093  13.48351877]
 [19.29784639 13.13372875 17.42500158]
 [11.38678213 16.7033279  13.68859268]]

- seed() is used to make random numbers repeatable.
- np.random.seed(number) --> can be any number
- Same seed → same random numbers
  Different seed → different numbers

In [97]:
# Remove duplicate from array
a=np.array([1,2,3,4,5,6,7,3,1])
print(np.unique(a))

[1 2 3 4 5 6 7]

In [102]:
np.sort(a)

array([1, 1, 2, 3, 3, 4, 5, 6, 7])

In [108]:
b = np.array([[1,2,3,4,5,6,7,90,8],[100,20,30,40,50,60,70,80,90]])
print(np.sort(b,axis=0))
print(np.sort(b,axis=1))

[[  1   2   3   4   5   6   7  80   8]
 [100  20  30  40  50  60  70  90  90]]
[[  1   2   3   4   5   6   7   8  90]
 [ 20  30  40  50  60  70  80  90 100]]

## **PANDAS**

In [3]:
import pandas as pd

In [28]:
s = pd.Series([1,2,3,4,5,6,7,8,9])
# Create a Series with custom index.
s.index= ["num1",'num2','num3','num4','num5','num6','num7','num8','num9']
s.index

Index(['num1', 'num2', 'num3', 'num4', 'num5', 'num6', 'num7', 'num8', 'num9'], dtype='str')

In [5]:
# Create a Series from a list.
s = pd.Series([1,2,3,4,5,6,7,8,9])
# Create a Series with custom index.
s.index= ["num1",'num2','num3','num4','num5','num6','num7','num8','num9']
# Convert Series to list.
l  = list(s)
# Convert Series to NumPy array.
n = np.array(s)
print(s)
print(f"Series to list : {l}")
print(f"Series to NumPy array : {n}")

num1    1
num2    2
num3    3
num4    4
num5    5
num6    6
num7    7
num8    8
num9    9
dtype: int64
Series to list : [1, 2, 3, 4, 5, 6, 7, 8, 9]
Series to NumPy array : [1 2 3 4 5 6 7 8 9]

In [6]:
# Create a Series from dictionary.
s1 = pd.Series({"name":"satwik","age":21})
s1

name    satwik
age         21
dtype: object

In [7]:
# Create 2D structure using DataFrame.
df = pd.DataFrame({"name":"satwik","age":21},index=[1])
df

     name  age
1  satwik   21

In [14]:
# Read csv
students = pd.read_csv("students.csv",index_col=0)
orders= pd.read_csv("orders.csv",index_col=0)
employees = pd.read_csv("employees.csv",index_col=0)
attendance = pd.read_csv("attendance.csv",index_col=0)
departments_df = pd.read_csv("departments.csv")

In [9]:
# Select name column.
students[["name",'marks']]

              name  marks
student_id
1           Satwik   88.0
2             Ravi   76.0
3           Anjali   92.0
4            Priya   85.0
5             Aman   67.0
6            Kiran    NaN
7             Neha   92.0
8            Arjun   76.0
9             Riya   85.0
10           Varun   67.0

In [10]:
# Select rows 2–5.
students[1:5]

              name  age gender course  marks       city
student_id
2             Ravi   20      M    CSE   76.0  Hyderabad
3           Anjali   19      F     DS   92.0    Chennai
4            Priya   21      F     AI   85.0  Bangalore
5             Aman   20      M    CSE   67.0      Delhi

In [11]:
# Select alternate rows.
students[::2]

              name  age gender course  marks       city
student_id
1           Satwik   19      M     DS   88.0  Bangalore
3           Anjali   19      F     DS   92.0    Chennai
5             Aman   20      M    CSE   67.0      Delhi
7             Neha   19      F     DS   92.0    Chennai
9             Riya   21      F     AI   85.0        NaN

In [7]:
# Select using .iloc[].
students.iloc[[0]]
students.iloc[[0,1]]
students.iloc[0:5]
students.iloc[:,[0,1]]
students.iloc[0:5,[0,1]]
students.iloc[[0,1],0:5]
students.iloc[[1],[1]]
students.iloc[-3:]

            age
student_id
2            20

In [10]:
# select using loc[]
students.loc[[1]]
students.loc[[1,2,3,4,5]]
students.loc[[1,2,3,4,5],["name"]]
students.loc[:,["name","age"]]

              name  age
student_id
1           Satwik   19
2             Ravi   20
3           Anjali   19
4            Priya   21
5             Aman   20
6            Kiran   22
7             Neha   19
8            Arjun   20
9             Riya   21
10           Varun   20

In [14]:
# Data Inspection
students.head()
students.tail()
print(f"Describe:\n {students.describe()}")
print("-"*100)
students.info()
print("-"*100)
print(f'Shape: {students.shape}')
print("-"*100)
print(students.dtypes)
print("-"*100)
print(f"INDEX : {students.index}")
print("-"*100)
print(f"column names: {students.columns}")

Describe:
              age      marks
count  10.000000   9.000000
mean   20.100000  80.888889
std     0.994429   9.778093
min    19.000000  67.000000
25%    19.250000  76.000000
50%    20.000000  85.000000
75%    20.750000  88.000000
max    22.000000  92.000000
----------------------------------------------------------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 1 to 10
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     str
 1   age     10 non-null     int64
 2   gender  10 non-null     str
 3   course  10 non-null     str
 4   marks   9 non-null      float64
 5   city    9 non-null      str
dtypes: float64(1), int64(1), str(4)
memory usage: 612.0 bytes
----------------------------------------------------------------------------------------------------
Shape: (10, 6)
----------------------------------------------------------------------------------------------------
name          str
age         int64
gender        str
course        str
marks     float64
city          str
dtype: object
----------------------------------------------------------------------------------------------------
INDEX : RangeIndex(start=1, stop=11, step=1, name='student_id')
----------------------------------------------------------------------------------------------------
column names: Index(['name', 'age', 'gender', 'course', 'marks', 'city'], dtype='str')

In [15]:
# Adding columns
students['grade'] ='A'
students['pass/fail'] = 'pass'
employees['Bonus 5%'] = employees['salary'] * 0.05
orders['Total sales'] = orders['price'] * orders['quantity']

# Update values
students.loc[students['name']=='Satwik','marks'] = 92
students.loc[students['name']=='Riya','city'] = 'Kolkata'
students.loc[students['name'] == 'Satwik','age'] = 21
students.loc[students['name'] == 'Kiran','marks'] = 87

# Rename column names
students.rename(columns={'marks':'score'}, inplace=True)
students.rename(columns={'course':'Course','score':'Score','name':'Name','age':'Age','gender':'Gender','city':'City','grade':'Grade'}, inplace=True)

# Drop columns
employees.drop('Bonus 5%', axis=1, inplace=True)

In [16]:
# Sorting
students.sort_values('Score')
students.sort_values('Score', ascending=False)
students.sort_values('Name')
students.sort_values(['Age','Score'])
students.sort_values(['Age','Score'] , ascending=[True, False])

              Name  Age Gender Course  Score       City Grade pass/fail
student_id
3           Anjali   19      F     DS   92.0    Chennai     A      pass
7             Neha   19      F     DS   92.0    Chennai     A      pass
2             Ravi   20      M    CSE   76.0  Hyderabad     A      pass
8            Arjun   20      M    CSE   76.0  Hyderabad     A      pass
5             Aman   20      M    CSE   67.0      Delhi     A      pass
10           Varun   20      M     DS   67.0      Delhi     A      pass
1           Satwik   21      M     DS   92.0  Bangalore     A      pass
4            Priya   21      F     AI   85.0  Bangalore     A      pass
9             Riya   21      F     AI   85.0    Kolkata     A      pass
6            Kiran   22      M     AI   87.0     Mumbai     A      pass

In [17]:
# Filtering
students[students['Score'] > 80]
students[(students['Age'] > 19) & (students['Age'] < 20)]
students[(students["Score"] > 70) & (students["City"] == 'Chennai')]
students[students["City"] != 'Delhi']

employees[employees['salary'] > 50000]
employees[employees['department'] == 'IT']

orders[orders['category'] == 'Electronics']
orders[orders['quantity'] > 2]
orders[orders['price'] > 10000]

students[students["City"].isin(['Delhi','Chennai'])]

              Name  Age Gender Course  Score     City Grade pass/fail
student_id
3           Anjali   19      F     DS   92.0  Chennai     A      pass
5             Aman   20      M    CSE   67.0    Delhi     A      pass
7             Neha   19      F     DS   92.0  Chennai     A      pass
10           Varun   20      M     DS   67.0    Delhi     A      pass

In [18]:
print(f'Student marks mean: {students["Score"].mean()}')
print(f'Student marks median: {students["Score"].median()}')
print(f'Student marks mode: {students["Score"].mode()}')
print(f'Maximum Student marks: {students["Score"].max()}')
print(f'Minimum Student marks: {students["Score"].min()}')
print(f'Student marks std: {students["Score"].std()}')
print(f'Students variance: {students["Score"].var()}')
print(f'Sum of marks: {students['Score'].sum()}')
print(f"Percentile: \n{students['Score'].quantile([0.25, 0.5, 0.75])}")
students['Score'].agg(
    mean='mean',
    median='median',
    mode=lambda x: x.mode()[0],
    minimum='min',
    maximum='max',
    std='std'
)

Student marks mean: 81.9
Student marks median: 85.0
Student marks mode: 0    92.0
Name: Score, dtype: float64
Maximum Student marks: 92.0
Minimum Student marks: 67.0
Student marks std: 9.803060746521977
Students variance: 96.10000000000001
Sum of marks: 819.0
Percentile:
0.25    76.00
0.50    85.00
0.75    90.75
Name: Score, dtype: float64

mean       81.900000
median     85.000000
mode       92.000000
minimum    67.000000
maximum    92.000000
std         9.803061
Name: Score, dtype: float64

In [19]:
students['Score'].cummax()
students['Score'].cummin()
students['Score'].cumsum()
students['Score'].cumprod()

student_id
1     9.200000e+01
2     6.992000e+03
3     6.432640e+05
4     5.467744e+07
5     3.663388e+09
6     3.187148e+11
7     2.932176e+13
8     2.228454e+15
9     1.894186e+17
10    1.269104e+19
Name: Score, dtype: float64

In [18]:
# aggregate method : Used when you want to apply one or multiple built-in functions to a Series or DataFrame.

data = {'marks' : [93,53,93,48,53,63,76],
        'Department':["IT",'DS','AIML','DS','CS',"AIML","AIML"],
        "age": [19, 20, 21, 22, 21, 19, 19]}
dt = pd.DataFrame(data)

dt['Department'].aggregate(mode=lambda x:x.mode()[0])
dt['marks'].aggregate(['mean','median','min','max','std'])
dt[['marks','age']].aggregate(['mean','median','min','max','std'])

mode    AIML
Name: Department, dtype: str

In [20]:
students.dtypes

Name             str
Age            int64
Gender           str
Course           str
Score        float64
City             str
Grade            str
pass/fail        str
dtype: object

In [21]:
# apply method : Used when you want custom logic/function on data.
employees['bonus'] = employees['salary'].apply(lambda x:x*0.05)
students['pass/fail'] = students['Score'].apply(lambda x: "pass" if x>50 else "fail")

def grading(x):
    x = int(x)

    if 90 <= x <= 100:
        return "A"
    elif 80 <= x < 90:
        return "B"
    elif 70 <= x < 80:
        return "C"
    elif 60 <= x < 70:
        return "D"
    elif 50 <= x < 60:
        return "E"
    else:
        return "F"
students['Grade'] = students['Score'].apply(grading)
students['Score'].apply('sum')

np.float64(819.0)

In [22]:
# Value Counts
students['Gender'].value_counts()
students['Course'].value_counts()
students['City'].value_counts()
students['Score'].value_counts(bins=3)
orders['product'].value_counts()
orders['Total sales'].value_counts(normalize=True)

Total sales
50000     0.250
100000    0.125
75000     0.125
7500      0.125
6000      0.125
20000     0.125
4500      0.125
Name: proportion, dtype: float64

In [21]:
# Handling Missing Values
students.isnull()
students.isnull().any(axis=0)
students.isnull().sum()
students.fillna(students['Score'].mean())
students['City'].fillna('Unknown')
students.dropna()

Name         False
Age          False
Gender       False
Course       False
Score        False
City         False
Grade        False
pass/fail    False
dtype: bool

In [24]:
# Handle Duplicate values
students.duplicated()
students.drop_duplicates(subset= ['Name','City','Score'])

              Name  Age Gender Course  Score       City Grade pass/fail
student_id
1           Satwik   21      M     DS   92.0  Bangalore     A      pass
2             Ravi   20      M    CSE   76.0  Hyderabad     C      pass
3           Anjali   19      F     DS   92.0    Chennai     A      pass
4            Priya   21      F     AI   85.0  Bangalore     B      pass
5             Aman   20      M    CSE   67.0      Delhi     D      pass
6            Kiran   22      M     AI   87.0     Mumbai     B      pass
7             Neha   19      F     DS   92.0    Chennai     A      pass
8            Arjun   20      M    CSE   76.0  Hyderabad     C      pass
9             Riya   21      F     AI   85.0    Kolkata     B      pass
10           Varun   20      M     DS   67.0      Delhi     D      pass

In [25]:
# GroupBy
students.groupby('City')['Score'].mean().sort_values(ascending=False)
employees.groupby('department')['salary'].sum().sort_values(ascending=False)
students.groupby('City')['Name'].count().sort_values(ascending=False)
orders.groupby('category')['Total sales'].mean()
employees.groupby('department')['salary'].max().sort_values(ascending=False)

department
IT         70000
Finance    55000
HR         40000
Name: salary, dtype: int64

In [30]:
# Pivot Table
employees.pivot_table(values = 'salary', index = 'department')
students.pivot_table(values='Score', index = 'Gender', aggfunc=['sum','mean','median'])
attendance.pivot_table(values = 'status', index = 'date', columns='status', aggfunc='count')
students.pivot_table(values='Name', index='Course', columns='City', aggfunc='count', fill_value=0)
orders.pivot_table(values = 'Total sales', index='city', columns='category', aggfunc='sum', fill_value=0, margins=True, margins_name='Total')
students.pivot_table(values='Score', index = 'Gender', columns='City', aggfunc=['count','sum'], margins=True, fill_value = 0, margins_name='Total')

           count                                                    sum  \
City   Bangalore Chennai Delhi Hyderabad Kolkata Mumbai Total Bangalore
Gender
F              1       2     0         0       1      0     4      85.0
M              1       0     2         2       0      1     6      92.0
Total          2       2     2         2       1      1    10     177.0


City   Chennai  Delhi Hyderabad Kolkata Mumbai  Total
Gender
F        184.0    0.0       0.0    85.0    0.0  354.0
M          0.0  134.0     152.0     0.0   87.0  465.0
Total    184.0  134.0     152.0    85.0   87.0  819.0

#### JOINS

In [27]:
# Basic Joins
employees.merge(departments_df,on = 'department',how='inner')
employees.merge(departments_df,on="department",how='left')
employees.merge(departments_df,on="department",how='right')
employees.merge(departments_df,on="department",how='outer')

#Find employees without department info.
emp_dep = employees.merge(departments_df,on="department",how='left')
emp_dep[emp_dep['department'].isnull()]

# Find students who attended.
stu_atte = students.merge(attendance,on='student_id',how='inner')
stu_atte[stu_atte['status'] == 'Present']

# self join
same_city = students.merge(students,on='City')
same_city = same_city[same_city["Name_x"] != same_city["Name_y"]]
same_city

same_dep = employees.merge(employees,on='department')
same_dep = same_dep[same_dep['name_x'] != same_dep['name_y']]
same_dep

,name_x,department,salary_x,experience_x,bonus_x,name_y,salary_y,experience_y,bonus_y
1,Amit,HR,35000,2,1750.0,Emma,40000,3,2000.0
3,John,IT,60000,5,3000.0,David,70000,6,3500.0
5,Sara,Finance,55000,4,2750.0,Raj,50000,4,2500.0
6,David,IT,70000,6,3500.0,John,60000,5,3000.0
8,Emma,HR,40000,3,2000.0,Amit,35000,2,1750.0
10,Raj,Finance,50000,4,2500.0,Sara,55000,4,2750.0

In [28]:
emp_dep=employees.merge(departments_df,on = 'department',how='inner')
emp_dep.count()
emp_dep.isnull().sum()

name          0
department    0
salary        0
experience    0
bonus         0
manager       0
dtype: int64

In [29]:
# Rename overlapping columns after merge.
stu_stu = students.merge(students,on='student_id')
stu_stu.rename(columns={'Name_x':'Name','City_x':'City','Score_x':'Score'})

,Name,Age_x,Gender_x,Course_x,Score,City,Grade_x,pass/fail_x,Name_y,Age_y,Gender_y,Course_y,Score_y,City_y,Grade_y,pass/fail_y
student_id,,,,,,,,,,,,,,,,
1,Satwik,21,M,DS,92.0,Bangalore,A,pass,Satwik,21,M,DS,92.0,Bangalore,A,pass
2,Ravi,20,M,CSE,76.0,Hyderabad,C,pass,Ravi,20,M,CSE,76.0,Hyderabad,C,pass
3,Anjali,19,F,DS,92.0,Chennai,A,pass,Anjali,19,F,DS,92.0,Chennai,A,pass
4,Priya,21,F,AI,85.0,Bangalore,B,pass,Priya,21,F,AI,85.0,Bangalore,B,pass
5,Aman,20,M,CSE,67.0,Delhi,D,pass,Aman,20,M,CSE,67.0,Delhi,D,pass
6,Kiran,22,M,AI,87.0,Mumbai,B,pass,Kiran,22,M,AI,87.0,Mumbai,B,pass
7,Neha,19,F,DS,92.0,Chennai,A,pass,Neha,19,F,DS,92.0,Chennai,A,pass
8,Arjun,20,M,CSE,76.0,Hyderabad,C,pass,Arjun,20,M,CSE,76.0,Hyderabad,C,pass
9,Riya,21,F,AI,85.0,Kolkata,B,pass,Riya,21,F,AI,85.0,Kolkata,B,pass
10,Varun,20,M,DS,67.0,Delhi,D,pass,Varun,20,M,DS,67.0,Delhi,D,pass

In [30]:
students.merge(attendance,on="student_id",suffixes=("_student","_attendance"))

,Name,Age,Gender,Course,Score,City,Grade,pass/fail,date,status
student_id,,,,,,,,,,
1,Satwik,21,M,DS,92.0,Bangalore,A,pass,2024-01-01,Present
2,Ravi,20,M,CSE,76.0,Hyderabad,C,pass,2024-01-01,Absent
3,Anjali,19,F,DS,92.0,Chennai,A,pass,2024-01-01,Present
4,Priya,21,F,AI,85.0,Bangalore,B,pass,2024-01-01,Present
5,Aman,20,M,CSE,67.0,Delhi,D,pass,2024-01-01,Absent

In [31]:
# Merge and remove duplicates.
stu_atte = students.merge(attendance,on='student_id',how='inner')
stu_atte.drop_duplicates()

,Name,Age,Gender,Course,Score,City,Grade,pass/fail,date,status
student_id,,,,,,,,,,
1,Satwik,21,M,DS,92.0,Bangalore,A,pass,2024-01-01,Present
2,Ravi,20,M,CSE,76.0,Hyderabad,C,pass,2024-01-01,Absent
3,Anjali,19,F,DS,92.0,Chennai,A,pass,2024-01-01,Present
4,Priya,21,F,AI,85.0,Bangalore,B,pass,2024-01-01,Present
5,Aman,20,M,CSE,67.0,Delhi,D,pass,2024-01-01,Absent

In [32]:
# Merge students and attendance, keep only name, status.
stu_atte = students.merge(attendance,on='student_id',how='inner')
stu_atte.loc[stu_atte['status'] == 'Present',['Name','status']]

              Name   status
student_id
1           Satwik  Present
3           Anjali  Present
4            Priya  Present

In [33]:
# Merge three tables together.
students.merge(attendance,on='student_id',how='inner').merge(orders,on='date',how='inner')

Empty DataFrame
Columns: [Name, Age, Gender, Course, Score, City, Grade, pass/fail, date, status, product, category, price, quantity, city, Total sales]
Index: []

#### FILTERING JOINS

In [495]:
# Semi Join → Find matching records.
students[students['City'].isin(orders['city'])]
employees[employees['department'].isin(departments_df['department'])]
students[students.index.isin(attendance.index)]


# Anti Join → Find missing records.
students[~students['City'].isin(orders['city'])]
departments_df[~departments_df['department'].isin(employees['department'])]
students[~students.index.isin(attendance.index)]

             Name  Age Gender Course  Score       City Grade pass/fail
student_id
6           Kiran   22      M     AI   87.0     Mumbai     B      pass
7            Neha   19      F     DS   92.0    Chennai     A      pass
8           Arjun   20      M    CSE   76.0  Hyderabad     C      pass
9            Riya   21      F     AI   85.0    Kolkata     B      pass
10          Varun   20      M     DS   67.0      Delhi     D      pass

#### concatenate

In [503]:
pd.concat([students,attendance],axis=1,ignore_index=True)

                 0   1  2    3     4          5  6     7           8        9
student_id
1           Satwik  21  M   DS  92.0  Bangalore  A  pass  2024-01-01  Present
2             Ravi  20  M  CSE  76.0  Hyderabad  C  pass  2024-01-01   Absent
3           Anjali  19  F   DS  92.0    Chennai  A  pass  2024-01-01  Present
4            Priya  21  F   AI  85.0  Bangalore  B  pass  2024-01-01  Present
5             Aman  20  M  CSE  67.0      Delhi  D  pass  2024-01-01   Absent
6            Kiran  22  M   AI  87.0     Mumbai  B  pass         NaN      NaN
7             Neha  19  F   DS  92.0    Chennai  A  pass         NaN      NaN
8            Arjun  20  M  CSE  76.0  Hyderabad  C  pass         NaN      NaN
9             Riya  21  F   AI  85.0    Kolkata  B  pass         NaN      NaN
10           Varun  20  M   DS  67.0      Delhi  D  pass         NaN      NaN

In [505]:
pd.concat([students,attendance],axis=0)

,Name,Age,Gender,Course,Score,City,Grade,pass/fail,date,status
student_id,,,,,,,,,,
1,Satwik,21.0,M,DS,92.0,Bangalore,A,pass,NaN,NaN
2,Ravi,20.0,M,CSE,76.0,Hyderabad,C,pass,NaN,NaN
3,Anjali,19.0,F,DS,92.0,Chennai,A,pass,NaN,NaN
4,Priya,21.0,F,AI,85.0,Bangalore,B,pass,NaN,NaN
5,Aman,20.0,M,CSE,67.0,Delhi,D,pass,NaN,NaN
6,Kiran,22.0,M,AI,87.0,Mumbai,B,pass,NaN,NaN
7,Neha,19.0,F,DS,92.0,Chennai,A,pass,NaN,NaN
8,Arjun,20.0,M,CSE,76.0,Hyderabad,C,pass,NaN,NaN
9,Riya,21.0,F,AI,85.0,Kolkata,B,pass,NaN,NaN
10,Varun,20.0,M,DS,67.0,Delhi,D,pass,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01,Present
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01,Absent
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01,Present
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01,Present
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01,Absent

In [507]:
df1 = pd.DataFrame({
    "Name": ["Satwik", "Ravi"],
    "Marks": [88, 76]
})

df2 = pd.DataFrame({
    "Name": ["Anjali", "Priya"],
    "Marks": [92, 85]
})

result = pd.concat([df1, df2], keys=["Class_A", "Class_B"])
result

             Name  Marks
Class_A 0  Satwik     88
        1    Ravi     76
Class_B 0  Anjali     92
        1   Priya     85

In [508]:
result.reset_index()

   level_0  level_1    Name  Marks
0  Class_A        0  Satwik     88
1  Class_A        1    Ravi     76
2  Class_B        0  Anjali     92
3  Class_B        1   Priya     85

In [31]:
pd.concat([students,attendance],axis=1,ignore_index=True,verify_integrity=True)

                 0   1  2    3     4          5  6     7           8        9
student_id
1           Satwik  21  M   DS  92.0  Bangalore  A  pass  2024-01-01  Present
2             Ravi  20  M  CSE  76.0  Hyderabad  A  pass  2024-01-01   Absent
3           Anjali  19  F   DS  92.0    Chennai  A  pass  2024-01-01  Present
4            Priya  21  F   AI  85.0  Bangalore  A  pass  2024-01-01  Present
5             Aman  20  M  CSE  67.0      Delhi  A  pass  2024-01-01   Absent
6            Kiran  22  M   AI  87.0     Mumbai  A  pass         NaN      NaN
7             Neha  19  F   DS  92.0    Chennai  A  pass         NaN      NaN
8            Arjun  20  M  CSE  76.0  Hyderabad  A  pass         NaN      NaN
9             Riya  21  F   AI  85.0    Kolkata  A  pass         NaN      NaN
10           Varun  20  M   DS  67.0      Delhi  A  pass         NaN      NaN

#### merge_ordered

In [518]:
gdp = pd.DataFrame({
    "year":[2020,2021,2022],
    "gdp":[10,12,15]
})
population = pd.DataFrame({
    "year":[2020,2022],
    "pop":[100,110]
})
pd.merge_ordered(population,gdp,on="year")

   year    pop  gdp
0  2020  100.0   10
1  2021    NaN   12
2  2022  110.0   15

#### merge_asof()

In [522]:
orders = pd.DataFrame({
    "time":[1,5,10]
})
prices = pd.DataFrame({
    "time":[2,6,8],
    "price":[100,120,150]
})
pd.merge_asof(orders,prices,on="time")

   time  price
0     1    NaN
1     5  100.0
2    10  150.0

#### MELT

In [524]:
sales = pd.DataFrame({
    "product":["A"],
    "Jan":[100],
    "Feb":[150],
    "Mar":[200]
})
sales

  product  Jan  Feb  Mar
0       A  100  150  200

In [525]:
sales.melt(id_vars="product",
           var_name="month",
           value_name="sales")

  product month  sales
0       A   Jan    100
1       A   Feb    150
2       A   Mar    200

#### QUERY

In [42]:
students.query('Score > 80')
students.query('City == "Chennai"')
students.query('City == "Chennai" and Score > 80')
students.query('Age < 21 and Age > 18')
students.query('Gender == "Male" or Grade == "F" ')

Empty DataFrame
Columns: [Name, Age, Gender, Course, Score, City, Grade, pass/fail]
Index: []